# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: starscout/errors.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "starscout.ValidationErrors" do
    repeated :errors, :message, 1, "starscout.ValidationError"
  end
  add_message "starscout.ValidationError" do
    optional :attribute, :string, 1
    optional :message, :string, 2
  end
end

module Starscout
  ValidationErrors = Google::Protobuf::DescriptorPool.generated_pool.lookup("starscout.ValidationErrors").msgclass
  ValidationError = Google::Protobuf::DescriptorPool.generated_pool.lookup("starscout.ValidationError").msgclass
end
