# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: starscout/match.proto

require 'google/protobuf'

require 'starscout/errors_pb'
require 'starscout/pagination_pb'
require 'starscout/uuid_pb'
require 'google/protobuf/wrappers_pb'
require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("starscout/match.proto", :syntax => :proto3) do
    add_message "starscout.Match" do
      optional :table, :uint32, 1
      optional :player1_id, :message, 2, "starscout.UUID"
      optional :player2_id, :message, 3, "starscout.UUID"
      optional :winner_id, :message, 4, "starscout.UUID"
      optional :draw, :bool, 5
      optional :bye, :bool, 6
      optional :last_modified_at, :message, 7, "google.protobuf.Timestamp"
    end
    add_message "starscout.GetMatchesRequest" do
      optional :event_id, :message, 1, "starscout.UUID"
      optional :round_number, :uint32, 2
      optional :page, :message, 3, "google.protobuf.UInt32Value"
      optional :per_page, :message, 4, "google.protobuf.UInt32Value"
    end
    add_message "starscout.GetMatchesResponse" do
      repeated :matches, :message, 1, "starscout.Match"
      optional :pagination, :message, 2, "starscout.Pagination"
    end
    add_message "starscout.GetMatchRequest" do
      optional :event_id, :message, 1, "starscout.UUID"
      optional :round_number, :uint32, 2
      optional :table, :uint32, 3
    end
    add_message "starscout.GetMatchResponse" do
      optional :match, :message, 1, "starscout.Match"
    end
    add_message "starscout.UpsertMatchRequest" do
      optional :event_id, :message, 1, "starscout.UUID"
      optional :round_number, :uint32, 2
      optional :table, :uint32, 3
      optional :player1_id, :message, 4, "starscout.UUID"
      optional :player2_id, :message, 5, "starscout.UUID"
      optional :winner_id, :message, 6, "starscout.UUID"
      optional :draw, :bool, 7
      optional :last_modified_at, :message, 8, "google.protobuf.Timestamp"
    end
    add_message "starscout.UpsertMatchResponse" do
      oneof :response do
        optional :match, :message, 1, "starscout.Match"
        optional :errors, :message, 2, "starscout.ValidationErrors"
      end
    end
    add_message "starscout.DeleteMatchRequest" do
      optional :event_id, :message, 1, "starscout.UUID"
      optional :round_number, :uint32, 2
      optional :table, :uint32, 3
    end
    add_message "starscout.DeleteMatchResponse" do
      oneof :response do
        optional :match, :message, 1, "starscout.Match"
        optional :errors, :message, 2, "starscout.ValidationErrors"
      end
    end
  end
end

module Starscout
  Match = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("starscout.Match").msgclass
  GetMatchesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("starscout.GetMatchesRequest").msgclass
  GetMatchesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("starscout.GetMatchesResponse").msgclass
  GetMatchRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("starscout.GetMatchRequest").msgclass
  GetMatchResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("starscout.GetMatchResponse").msgclass
  UpsertMatchRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("starscout.UpsertMatchRequest").msgclass
  UpsertMatchResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("starscout.UpsertMatchResponse").msgclass
  DeleteMatchRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("starscout.DeleteMatchRequest").msgclass
  DeleteMatchResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("starscout.DeleteMatchResponse").msgclass
end
