# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: starscout/service.proto

require 'google/protobuf'

require 'starscout/event_pb'
require 'starscout/player_pb'
require 'starscout/round_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("starscout/service.proto", :syntax => :proto3) do
  end
end

module Starscout
end
