# Code generated by protoc-gen-twirp_ruby 1.11.0, DO NOT EDIT.
require 'twirp'
require_relative 'service_pb.rb'

module Starscout
  class StarscoutService < ::Twirp::Service
    package 'starscout'
    service 'Starscout'
    rpc :GetEvents, GetEventsRequest, GetEventsResponse, :ruby_method => :get_events
    rpc :GetEvent, GetEventRequest, GetEventResponse, :ruby_method => :get_event
    rpc :GetPlayers, GetPlayersRequest, GetPlayersResponse, :ruby_method => :get_players
    rpc :GetPlayer, GetPlayerRequest, GetPlayerResponse, :ruby_method => :get_player
    rpc :UpsertPlayer, UpsertPlayerRequest, UpsertPlayerResponse, :ruby_method => :upsert_player
    rpc :DeletePlayer, DeletePlayerRequest, DeletePlayerResponse, :ruby_method => :delete_player
    rpc :GetRounds, GetRoundsRequest, GetRoundsResponse, :ruby_method => :get_rounds
    rpc :GetRound, GetRoundRequest, GetRoundResponse, :ruby_method => :get_round
    rpc :UpsertRound, UpsertRoundRequest, UpsertRoundResponse, :ruby_method => :upsert_round
    rpc :DeleteRound, DeleteRoundRequest, DeleteRoundResponse, :ruby_method => :delete_round
  end

  class StarscoutClient < ::Twirp::Client
    client_for StarscoutService
  end
end
